### ISSUE TITLE
Cannot compile tex due to missing figures

### ISSUE THREAD

**Issue by StarostinV** [arm61/reporting_sampling#7]
Unfortunately, I cannot compile the tex file to check my modifications before opening a pull request, because the src/tex/figures folder in the main branch does not seem to have any figures. If I understand it correctly, I would have to run python scripts to generate the figures locally, but for that I would probably have to generate the data as well (for instance, for the corner plot) since the data folder is also empty. 

Would it be possible to add figures to the repo? Or am I missing something? Of course, otherwise I can just make pull requests without compiling the tex. Thank you!

**Comment by arm61** [comment]
The repo uses `showyourwork` to enable a reproducible paper. Details are available here https://show-your.work/. But if you wanna just open the PR without checking it compiles then I am happy with that too.

**Comment by arm61** [comment]
I’ll add something to the README tomorrow mentioning this fact! Cheers for reminding me.

**Comment by arm61** [comment]
I have added something to the README with explains this, will close this issue but please reopen if you think it is insufficient.

**Comment by StarostinV** [comment]
Thank you!
